### ISSUE TITLE
CSS/HTML ? 

### ISSUE THREAD

**Issue by markediez** [shanglu9425/Roles-Management-Mock-up#23]
The assign-panel is funky. If you scroll down. Then go hover over it then hover outside, you will see what I mean.

**Comment by shanglu9425** [comment]
I found the problem.
The group drop down JQuery is messing it up the "overflow-y: auto;"

**Comment by shanglu9425** [comment]
fixed! Looks like we are missing a "overflow-y:hidden"  :)!!!! took me forever to spot that problem
